# -- Google cloud project details --
google_cloud:
    project_id: "juristab"
    region: "us"
    processor_id: "c60807664382dc8" 

# -- Database connection details --
database:
    source:
        dialect: "mysql"
        driver: "mysqlconnector"
        host: "juris-data.crkmq80swpic.ap-southeast-2.rds.amazonaws.com"
        port: "3306"
        name: "legal_source"

    destination:
        dialect: "mysql"
        driver: "mysqlconnector"
        host: "juris-data.crkmq80swpic.ap-southeast-2.rds.amazonaws.com"
        port: "3306"
        name: "legal_store"

# -- AWS connection details --
aws:
    default_region: "ap-southeast-2"
    s3:
        bucket_name: "legal-store"
        sub_folder_caselaw: "case-laws/"
        sub_folder_legislation: "legislation/"
  

# -- File naming conventions for the enrichment service --
enrichment_filenames:
  source_text: "miniviewer.txt"
  embedding_output: "embeddings.npy"

# -- Registry details
tables_registry:
    database: "legal_store"
    table_caselaw: "caselaw_registry"
    table_legislation: "legislation_registry"
    column: "year"
    processing_years: []
    jurisdiction_codes: ['ACT','VIC','NT','QLD','WA','SA','TAS','FED','NSW']

# -- Embedding switch
embedding:
    caselaw: true
    legislation: true
