# -- Google cloud project details --
google_cloud:
    project_id: "juristab"
    region: "us"
    processor_id: "c60807664382dc8" 

# -- Database connection details --
database:
    source:
        dialect: "mysql"
        driver: "mysqlconnector"
        host: "juris-data.crkmq80swpic.ap-southeast-2.rds.amazonaws.com"
        port: "3306"
        name: "legal_source"

    destination:
        dialect: "mysql"
        driver: "mysqlconnector"
        host: "juris-data.crkmq80swpic.ap-southeast-2.rds.amazonaws.com"
        port: "3306"
        name: "legal_store"

# -- AWS connection details --
aws:
    default_region: "ap-southeast-2"
    s3:
        bucket_name: "legal-store"
    
# List of tables to be read by the connector
tables:
  tables_to_read:
    - database: legal_store
      table: caselaw_registry
      
  tables_to_write:
    - database: legal_store
      table: caselaw_enrichment_status
      columns:
        processing_status: "status_jurislink"
        processing_duration: "duration_jurislink"
        start_time: "start_time_jurislink"
        end_time: "end_time_jurislink"
    - database: legal_store
      key: "juris_link"
      table: juris_link_extract_from_caselaw

# -- File naming conventions for the enrichment service --
enrichment_filenames:
  source_file: "miniviewer.html"

# -- Registry details
tables_registry:
    database: "legal_store"
    table: "caselaw_registry"
    column: "year"
    processing_years: []
    jurisdiction_codes: ['ACT','VIC','NT','QLD','WA','SA','TAS','NSW','FED']
